[tool.poetry]
name = "stackmorelayers"
version = "0.0.5"
description = "My personal ML library"
authors = ["Andrew Sonin <sonin.cel@yandex.ru>"]
repository = "https://github.com/andrewsonin/stackmorelayers"
homepage = "https://github.com/andrewsonin/stackmorelayers"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.21"
pandas = "^1.3.3"
matplotlib = "^3.4.3"
scikit-learn = "^1.0"
lightgbm = "^3.2.1"
catboost = "^0.26.1"
statsmodels = "^0.12.2"
tqdm = "^4.62.3"

[tool.poetry.dev-dependencies]
ipython = "^7.28.0"
jupyter = "^1.0.0"
jupyterlab = "^3.1.13"
mypy = ">=0.910"

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools>=57"]
build-backend = "poetry.core.masonry.api"
