[tool.poetry]
name = "envex"
version = "1.1.1"
description = "An extended os.environ interface"
authors = ["David Nugent <davidn@uniquode.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-pythonpath = "*"

[tool.pytest.ini-options]
minversion = "6.0"
python_paths = [
    "envex"
]
testpaths = [
    "tests"
]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
