[tool.poetry]
name = "tykes"
version = "0.1.0"
description = "A python project designed to provide low-stimulation games to young children."
# long_description = file: README.md
# long_description_content_type = text/markdown
authors = ["Ian Wernecke <you@example.com>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.8"
typer = "^0.4.0"
pygame = "^2.0.2"
loguru = "^0.5.3"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
isort = "^5.9.3"

[tool.poetry.scripts]
tykes = "tykes.cli:app"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

